version: '3.3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: on-failure
    build: ./docker/Dockerfiles/nginx/.
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/share/nginx/html
    depends_on:
      - php

  php:
    image: php:7.2-fpm
    container_name: php
    restart: on-failure
    build: ./docker/Dockerfiles/php/.
    working_dir: /usr/share/nginx/html
    volumes:
      - ./:/usr/share/nginx/html
